//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletId { get; set; }
        public int FestivalId { get; set; }
        public int BiletTurId { get; set; }
        public Nullable<int> Fiyat { get; set; }
    
        public virtual Festival Festival { get; set; }
        public virtual FestivalTuru FestivalTuru { get; set; }
    }
}
