//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiBilgi
    {
        public string AdSoyad { get; set; }
        public int KimlikNo { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string KullaniciAd { get; set; }
        public Nullable<int> YetkiId { get; set; }
    
        public virtual Yetki Yetki { get; set; }
    }
}
