//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatis.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebProjeEntities : DbContext
    {
        public WebProjeEntities()
            : base("name=WebProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<BiletTuru> BiletTuru { get; set; }
        public virtual DbSet<Festival> Festival { get; set; }
        public virtual DbSet<FestivalTuru> FestivalTuru { get; set; }
        public virtual DbSet<KisiBilgi> KisiBilgi { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
