//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public string AdSoyad { get; set; }
        public string Festival { get; set; }
        public string BiletTuru { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
